"""user table

Revision ID: 378255e043e1
Revises: 63db412728cd
Create Date: 2023-08-20 20:05:13.031762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378255e043e1'
down_revision = '63db412728cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
