"""seeded

Revision ID: c5017cb04940
Revises: c7ca93f89669
Create Date: 2023-08-16 20:03:51.047614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5017cb04940'
down_revision = 'c7ca93f89669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('sneaker_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('sneaker_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
