"""updated tables

Revision ID: c7ca93f89669
Revises: 963452c8e533
Create Date: 2023-08-16 18:43:02.269006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ca93f89669'
down_revision = '963452c8e533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneakers', schema=None) as batch_op:
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneakers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
